%YAML:1.0
image_dir: "/home/tl/data/ss928/resource/images"
output_dir: "/home/tl/data/ss928/images"

# 使用合并模型模式 (推荐，推理更快)
use_merge: 1
merge_model: "../models/onnx/nanotrack_merge.onnx"

# 分离模型模式 (传统模式)
backbone: "../models/onnx/nanotrack_backbone.onnx"
search_backbone: "../models/onnx/nanotrack_backbone_search.onnx"
head: "../models/onnx/nanotrack_head.onnx"

use_cuda: 0
init_roi: [938, 527, 43, 31]
repeat: 10
